continue search on remaining files after error
In case of IllegalStateException with "Invalid BootstrapMethods attribute entry: 2 additional arguments required for method java/lang/invoke/StringConcatFactory.makeConcatWithConstants, but only 1 specified." this is a known issue of Procyon <= 0.5.35 and the available fix it not yet released, refer to https://bitbucket.org/mstrobel/procyon/issues/336/
The search does not stop anymore, simply a hint is given in found class list for that error.

In case of other IllegalStateException or general Exceptions hold on the search in remaining files, too.
For example, my openJDK 11 based WAR file has other error cases in Procyon too.
java.lang.IllegalArgumentException: Argument 'value' must be in the range [1, 18], but value was: 19.
java.lang.IllegalArgumentException: Argument 'value' must be in the range [1, 18], but value was: 20.

both at com.strobel.core.VerifyArgument.inRange(VerifyArgument.java:347)